<?php

namespace AppBundle\Repository;

/**
 * AnswerDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerDataRepository extends \Doctrine\ORM\EntityRepository
{
}
