<?php

namespace AppBundle\Repository;

/**
 * QuestionItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
