<?php

namespace AppBundle\Repository;

/**
 * QuestionTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
