<?php

namespace AppBundle\Repository;

/**
 * RightAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
