<?php

namespace AppBundle\Repository;

/**
 * ValidAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
